[env]
RUSTFLAGS = "-C target-cpu=cortex-a76 -C link-arg=--library-path=src/__board__/raspberrypi -C link-arg=--script=kernel.ld"

[tasks.mint]
script = "RUSTFLAGS=${RUSTFLAGS} cargo rustc --release"

[tasks.strip]
script = "cargo objcopy --release  -- --strip-all -O binary target/kernel_2712.img"

[tasks.sync]
dependencies = ["mint", "strip"]
command = "cp"
args = ["target/kernel_2712.img", "/Volumes/bootfs/kernel_2712.img"]
